# This file was generated by the {rix} R package v0.17.2 on 2026-02-25
# with following call:
# >rix(date = "2026-01-05",
#  > r_pkgs = c("duckdb",
#  > "dplyr",
#  > "ggplot2",
#  > "jsonlite",
#  > "blastula",
#  > "here",
#  > "scales",
#  > "tibble",
#  > "lubridate"),
#  > ide = "none",
#  > project_path = "/Users/johngavin/docs_gh/proj/data/llm/telemetry",
#  > overwrite = TRUE,
#  > shell_hook = "echo 'Welcome to llmtelemetry app shell'",
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-01-05.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      blastula
      dplyr
      duckdb
      ggplot2
      here
      jsonlite
      lubridate
      scales
      tibble;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    shellHook = "echo 'Welcome to llmtelemetry app shell'";
  }; 
in
  {
    inherit pkgs shell;
  }
