# This file was generated by the {rix} R package v0.18.1 on 2026-05-12
# with following call:
# >rix(date = "2026-01-05",
#  > r_pkgs = c("duckdb",
#  > "duckplyr",
#  > "dplyr",
#  > "tidyr",
#  > "ggplot2",
#  > "jsonlite",
#  > "blastula",
#  > "here",
#  > "scales",
#  > "tibble",
#  > "lubridate",
#  > "checkmate",
#  > "cli",
#  > "DBI",
#  > "purrr",
#  > "pkgload",
#  > "devtools",
#  > "testthat",
#  > "otel"),
#  > system_pkgs = c("cmake",
#  > "protobuf_21",
#  > "pkg-config"),
#  > ide = "none",
#  > project_path = "/Users/johngavin/docs_gh/llmtelemetry",
#  > overwrite = TRUE,
#  > shell_hook = "echo 'Welcome to llmtelemetry app shell'; source $PWD/.nix-shellhook.sh 2>/dev/null || true",
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-01-05.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      blastula
      checkmate
      cli
      DBI
      devtools
      dplyr
      duckdb
      duckplyr
      ggplot2
      here
      jsonlite
      lubridate
      otel
      pkgload
      purrr
      scales
      testthat
      tibble
      tidyr;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs)
      cmake
      glibcLocales
      nix
      pkg-config
      protobuf_21
      R;
  };

  # otelsdk: GitHub-only (not on CRAN). Requires cmake + protobuf_21 at build time.
  # nativeBuildInputs supplies the cmake/protobuf toolchain to the nix derivation build env.
  # rev pinned to otelsdk 0.2.4.9000 (2026-05-11). Update when new release available.
  otelsdk = pkgs.rPackages.buildRPackage {
    name = "otelsdk";
    src = pkgs.fetchgit {
      url = "https://github.com/r-lib/otelsdk";
      rev = "0cf2ad93631944d28142e941ae9ac5cab107f478";
      sha256 = "sha256-xYKmrniWGBx9TaoMOxqGpgd2FEG4fU8DP279APmk2sU=";
    };
    nativeBuildInputs = [ pkgs.cmake pkgs.protobuf_21 pkgs.pkg-config ];
    propagatedBuildInputs = builtins.attrValues {
      inherit (pkgs.rPackages) otel;
    };
  };

  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages otelsdk ];
    shellHook = ''
    echo 'Welcome to llmtelemetry app shell'; source $PWD/.nix-shellhook.sh 2>/dev/null || true
  '';
  }; 
in
  {
    inherit pkgs shell;
  }
