test_that("no filesystem-path-style strings in committed extdata", {
  # Use testthat::test_path() to locate the package root correctly whether
  # running via devtools::test(), R CMD check, or in a git worktree.
  pkg_root <- normalizePath(file.path(test_path(), "..", ".."), mustWork = FALSE)
  extdata_dir    <- file.path(pkg_root, "inst", "extdata")
  parquet_dir    <- file.path(pkg_root, "inst", "extdata", "telemetry")

  json_files <- list.files(extdata_dir, pattern = "\\.json$", full.names = TRUE)
  parquet_files <- list.files(parquet_dir, pattern = "\\.parquet$",
                              recursive = TRUE, full.names = TRUE)

  # Patterns that indicate private filesystem paths or leaked project names.
  # IMPORTANT: keep in sync with SENSITIVE_VERIFY_PATTERNS in
  # inst/scripts/sanitize_ccusage_all.R so the regression gate here cannot
  # pass while leaks remain (Finding 1, issue #140).
  forbidden_patterns <- c(
    "-Users-johngavin",     # raw home-dir prefix
    "[A-Za-z0-9]{8,}/repo", # agent-worktree-id/repo style
    "[A-Za-z0-9]{8,}-repo", # dash-form agent worktree (e.g. "D73dOZsvyf-repo")
    "pers-NHS",             # specific medical project leak
    "antigravity",          # specific leaked name
    "-private-tmp-",        # macOS /private/tmp worktree paths (issue #140)
    "-tmp-",                # generic /tmp worktree paths (Finding 1, issue #140)
    "worktree-[0-9]+",      # numeric-suffix worktree identifiers (issue #140)
    "worktree-agent-",      # named agent worktree identifiers (Finding 1, issue #140)
    "johngavin"             # bare username anywhere (Finding 1, issue #140)
  )

  # Patterns that are allowed in commit MESSAGE fields only (author-written text,
  # not filesystem path leaks):
  #   - "johngavin" in commit messages (e.g. "fix: check johngavin cache")
  #   - "JohnGavin" in PR merge messages (e.g. "from JohnGavin/fix-issue-...")
  #   - branch names containing "worktree-agent-" in merge-commit messages
  # These are column-specific allowances.  Structured columns (project,
  # canonical_project, hash, date, etc.) remain fully scanned.
  commit_message_allowed_patterns <- c(
    "johngavin",         # appears in author-written commit messages
    "JohnGavin",         # appears in PR merge commit messages
    "worktree-agent-"    # appears in branch references in merge-commit messages
  )
  # Which fields in git commit data are commit message text:
  commit_message_fields_json    <- "message"     # key name in JSON array
  commit_message_field_parquet  <- "message"     # column name in parquet

  # JSON files to skip entirely (not generated by export_dashboard_data.R):
  # - ccusage_daily_raw_*: legacy raw snapshots
  # - github_issue_events.json: raw GH API dump with English phrases that match
  #   the agent-worktree regex but are not path leaks
  # - test.json: scratch/developer file
  # NOTE: git_commits_by_project.json is NO LONGER skipped wholesale (round-3
  # Finding B fix).  Its "message" field is allowed to contain author-written
  # patterns; all other fields (project, canonical_project, hash, date, …) are
  # fully scanned.  See field-specific logic below.
  # NOTE: ccusage_daily_all.json, ccusage_session_all.json, and
  # ccusage_blocks_all.json are sanitized and MUST be scanned.
  skip_basenames <- c(
    "ccusage_daily_raw_20260220.json",
    "ccusage_daily_raw_20260221.json",
    "github_issue_events.json",
    "test.json"
  )
  json_files <- json_files[!basename(json_files) %in% skip_basenames]

  con <- DBI::dbConnect(duckdb::duckdb())
  on.exit(DBI::dbDisconnect(con, shutdown = TRUE), add = TRUE)

  for (f in json_files) {
    is_commit_file <- basename(f) == "git_commits_by_project.json"

    if (!is_commit_file) {
      # Standard whole-file scan — every pattern must be absent.
      content <- readLines(f, warn = FALSE)
      text <- paste(content, collapse = "\n")
      for (pat in forbidden_patterns) {
        expect_false(
          grepl(pat, text, perl = TRUE),
          info = sprintf("%s contains forbidden pattern '%s'", basename(f), pat)
        )
      }
    } else {
      # git_commits_by_project.json: field-specific scan.
      # "message" field may contain author-written references (not path leaks);
      # all other fields are fully scanned.
      commits <- jsonlite::fromJSON(f, simplifyDataFrame = TRUE)
      # Scan non-message columns (project, canonical_project, hash, date, etc.)
      non_msg_cols <- setdiff(names(commits), commit_message_fields_json)
      for (col in non_msg_cols) {
        if (is.character(commits[[col]])) {
          col_text <- paste(commits[[col]], collapse = "\n")
          for (pat in forbidden_patterns) {
            expect_false(
              grepl(pat, col_text, perl = TRUE),
              info = sprintf("%s column '%s' contains forbidden pattern '%s'",
                             basename(f), col, pat)
            )
          }
        }
      }
      # For the message field: only scan patterns NOT in the allowlist.
      strict_patterns <- setdiff(forbidden_patterns, commit_message_allowed_patterns)
      msg_text <- paste(commits[[commit_message_fields_json]], collapse = "\n")
      for (pat in strict_patterns) {
        expect_false(
          grepl(pat, msg_text, perl = TRUE),
          info = sprintf("%s column 'message' contains non-allowed pattern '%s'",
                         basename(f), pat)
        )
      }
    }
  }

  # Parquet files: read each into a data frame, check string columns for patterns.
  # git_commits.parquet: NO LONGER skipped wholesale (round-3 Finding B fix).
  # Structured columns are fully scanned; the "message" column gets the same
  # field-specific allowlist as git_commits_by_project.json above.
  for (pf in parquet_files) {
    is_commit_file <- basename(pf) == "git_commits.parquet"
    df <- DBI::dbGetQuery(con, sprintf("SELECT * FROM read_parquet('%s')", pf))

    for (col in names(df)) {
      if (!is.character(df[[col]])) next

      col_text <- paste(df[[col]], collapse = "\n")

      if (is_commit_file && col == commit_message_field_parquet) {
        # Message column in git_commits.parquet: allow author-written references.
        strict_patterns <- setdiff(forbidden_patterns, commit_message_allowed_patterns)
        for (pat in strict_patterns) {
          expect_false(
            grepl(pat, col_text, perl = TRUE),
            info = sprintf("%s column '%s' contains non-allowed pattern '%s'",
                           basename(pf), col, pat)
          )
        }
      } else {
        # All other columns (including project, canonical_project in commit file):
        # full scan with no allowances.
        for (pat in forbidden_patterns) {
          expect_false(
            grepl(pat, col_text, perl = TRUE),
            info = sprintf("%s column '%s' contains forbidden pattern '%s'",
                           basename(pf), col, pat)
          )
        }
      }
    }
  }
})

test_that("leak injected into non-message column of git_commits_by_project.json is caught (Finding B, #140 round-3)", {
  # Regression test: proves that removing the whole-file skip (round-3 fix)
  # means a leak in the 'project' column is now detected, even though 'message'
  # is allowed to contain author-written references.
  # Inject a fake path into the 'project' field and verify the scanner catches it.
  fake_commits <- data.frame(
    project           = c("-Users-johngavin-docs-gh-llm", "irishbuoys"),
    canonical_project = c("llm", "irishbuoys"),
    hash              = c("abc1234", "def5678"),
    date              = c("2026-05-01", "2026-05-02"),
    message           = c("fix: normal commit message", "feat: normal commit"),
    stringsAsFactors  = FALSE
  )

  forbidden_in_project <- "-Users-johngavin"

  # Check the project column (must be caught):
  project_text <- paste(fake_commits$project, collapse = "\n")
  expect_true(
    grepl(forbidden_in_project, project_text, perl = TRUE),
    label = "injected leak must be detectable in project column"
  )

  # Check the message column (no injected leak — the allowlist test is separate):
  message_text <- paste(fake_commits$message, collapse = "\n")
  expect_false(
    grepl(forbidden_in_project, message_text, perl = TRUE),
    label = "message column must not contain the injected project-column leak"
  )
})

test_that("leak injected into non-message column of git_commits.parquet is caught by field-specific scan (Finding B, #140 round-3)", {
  # Regression test: proves that removing the whole-file skip for git_commits.parquet
  # means a leak in 'project' or 'canonical_project' is detected even though
  # the 'message' column is allowed to contain author-written references.
  # Construct a minimal in-memory data frame with a leak in 'project'.
  pkg_root <- normalizePath(file.path(test_path(), "..", ".."), mustWork = FALSE)
  pf <- file.path(pkg_root, "inst", "extdata", "telemetry", "v1", "git_commits.parquet")
  skip_if(!file.exists(pf), "git_commits.parquet not present in extdata")

  con2 <- DBI::dbConnect(duckdb::duckdb())
  on.exit(DBI::dbDisconnect(con2, shutdown = TRUE), add = TRUE)

  df <- DBI::dbGetQuery(con2, sprintf("SELECT * FROM read_parquet('%s')", pf))

  # The project and canonical_project columns must contain only clean values.
  # If they have any forbidden pattern, the field-specific scan will catch it.
  # (This assertion verifies that those columns do NOT contain raw path leaks —
  # i.e. the data is clean, and the scanner would have caught it if it weren't.)
  forbidden_patterns_structural <- c(
    "-Users-johngavin",
    "johngavin",
    "-private-tmp-",
    "-tmp-",
    "worktree-agent-"
  )
  for (col in c("project", "canonical_project")) {
    if (!col %in% names(df)) next
    col_text <- paste(df[[col]], collapse = "\n")
    for (pat in forbidden_patterns_structural) {
      expect_false(
        grepl(pat, col_text, perl = TRUE),
        info = sprintf("git_commits.parquet column '%s' contains forbidden pattern '%s' — field-specific scan should have caught this", col, pat)
      )
    }
  }
})

test_that("committed extdata JSON files are valid JSON", {
  pkg_root <- normalizePath(file.path(test_path(), "..", ".."), mustWork = FALSE)
  extdata_dir <- file.path(pkg_root, "inst", "extdata")
  json_files <- list.files(extdata_dir, pattern = "\\.json$", full.names = TRUE)
  for (f in json_files) {
    result <- tryCatch(jsonlite::fromJSON(f), error = function(e) e)
    expect_false(
      inherits(result, "error"),
      info = sprintf("%s is not valid JSON: %s", basename(f), if (inherits(result, "error")) conditionMessage(result) else "")
    )
  }
})
