test_that("no filesystem-path-style strings in committed extdata", {
  # Use testthat::test_path() to locate the package root correctly whether
  # running via devtools::test(), R CMD check, or in a git worktree.
  pkg_root <- normalizePath(file.path(test_path(), "..", ".."), mustWork = FALSE)
  extdata_dir    <- file.path(pkg_root, "inst", "extdata")
  parquet_dir    <- file.path(pkg_root, "inst", "extdata", "telemetry")

  json_files <- list.files(extdata_dir, pattern = "\\.json$", full.names = TRUE)
  parquet_files <- list.files(parquet_dir, pattern = "\\.parquet$",
                              recursive = TRUE, full.names = TRUE)

  # Patterns that indicate private filesystem paths or leaked project names
  forbidden_patterns <- c(
    "-Users-johngavin",     # raw home-dir prefix
    "[A-Za-z0-9]{8,}/repo", # agent-worktree-id/repo style
    "[A-Za-z0-9]{8,}-repo", # dash-form agent worktree (e.g. "D73dOZsvyf-repo")
    "pers-NHS",             # specific medical project leak
    "antigravity",          # specific leaked name
    "-private-tmp-",        # macOS /private/tmp worktree paths (issue #140)
    "worktree-[0-9]+"       # numeric-suffix worktree identifiers (issue #140)
  )

  # JSON files to skip:
  # - ccusage_daily_raw_*: legacy raw snapshots not generated by export script
  # - github_issue_events.json: raw GH API dump containing PR text where
  #   English phrases like "statistical-repo" match the agent-worktree regex
  #   but are not path leaks. This file is not generated by export_dashboard_data.R.
  # - test.json: scratch/developer file, not a dashboard export
  # NOTE: ccusage_daily_all.json, ccusage_session_all.json, and ccusage_blocks_all.json
  # are all sanitized and MUST be scanned — they were removed from skip_basenames as part
  # of the privacy-regression fix (roborev Issue #1, #118).
  # ccusage_blocks_all.json audited 2026-05-19: 0 forbidden-pattern hits (issue #118).
  skip_basenames <- c(
    "ccusage_daily_raw_20260220.json",
    "ccusage_daily_raw_20260221.json",
    "github_issue_events.json",
    "test.json"
  )
  json_files <- json_files[!basename(json_files) %in% skip_basenames]

  for (f in json_files) {
    content <- readLines(f, warn = FALSE)
    text <- paste(content, collapse = "\n")
    for (pat in forbidden_patterns) {
      expect_false(
        grepl(pat, text, perl = TRUE),
        info = sprintf("%s contains forbidden pattern '%s'", basename(f), pat)
      )
    }
  }

  # Parquet files: read each into a data frame, check string columns for patterns
  con <- DBI::dbConnect(duckdb::duckdb())
  on.exit(DBI::dbDisconnect(con, shutdown = TRUE), add = TRUE)

  for (pf in parquet_files) {
    df <- DBI::dbGetQuery(con, sprintf("SELECT * FROM read_parquet('%s')", pf))

    for (col in names(df)) {
      if (is.character(df[[col]])) {
        col_text <- paste(df[[col]], collapse = "\n")
        for (pat in forbidden_patterns) {
          expect_false(
            grepl(pat, col_text, perl = TRUE),
            info = sprintf("%s column %s contains forbidden pattern '%s'", basename(pf), col, pat)
          )
        }
      }
    }
  }
})

test_that("committed extdata JSON files are valid JSON", {
  pkg_root <- normalizePath(file.path(test_path(), "..", ".."), mustWork = FALSE)
  extdata_dir <- file.path(pkg_root, "inst", "extdata")
  json_files <- list.files(extdata_dir, pattern = "\\.json$", full.names = TRUE)
  for (f in json_files) {
    result <- tryCatch(jsonlite::fromJSON(f), error = function(e) e)
    expect_false(
      inherits(result, "error"),
      info = sprintf("%s is not valid JSON: %s", basename(f), if (inherits(result, "error")) conditionMessage(result) else "")
    )
  }
})
