#!/usr/bin/env bash
# export_and_deploy_data.sh — Export local telemetry data and push to trigger deploy
# Called from session_stop.sh hook or manually
# Exports data that only exists locally (predictions, unified.duckdb, cmonitor-rs)
# then commits to llmtelemetry repo and pushes (CI deploys automatically)

set -uo pipefail

TELEMETRY_REPO="$HOME/docs_gh/llmtelemetry"
DATA_DIR="$TELEMETRY_REPO/vignettes/data"
EXPORT_SCRIPT="$TELEMETRY_REPO/inst/scripts/export_dashboard_data.R"
ROLLUP_SCRIPT="$TELEMETRY_REPO/inst/scripts/run_rollup.R"

# Quick check: is the repo available?
if [ ! -d "$TELEMETRY_REPO/.git" ]; then
  echo "TELEMETRY: repo not found at $TELEMETRY_REPO"
  exit 0
fi

# Check if export script exists
if [ ! -f "$EXPORT_SCRIPT" ]; then
  echo "TELEMETRY: export script not found"
  exit 0
fi

# Run export (from repo root so here::here() works)
echo "TELEMETRY: exporting dashboard data..."
(cd "$TELEMETRY_REPO" && timeout 120 Rscript "$EXPORT_SCRIPT" 2>&1) | tail -5

# Regenerate v1 parquets from the just-written JSON + drain staging (#210, #83)
# Non-fatal: log on failure so the existing export/commit still proceeds.
if [ -f "$ROLLUP_SCRIPT" ]; then
  echo "TELEMETRY: regenerating v1 parquets (run_rollup.R)..."
  if (cd "$TELEMETRY_REPO" && nix-shell "$TELEMETRY_REPO/default.nix" --run "Rscript '$ROLLUP_SCRIPT'" 2>&1) | tail -3; then
    # Stage regenerated parquets so they are included in the commit below
    git -C "$TELEMETRY_REPO" add inst/extdata/telemetry/v1/*.parquet 2>/dev/null || true
  else
    echo "TELEMETRY: run_rollup.R failed (non-fatal) — parquets not updated"
  fi
else
  echo "TELEMETRY: run_rollup.R not found — skipping parquet regeneration"
fi

# Check if any data files changed (vignettes/data/ OR v1 parquets)
CHANGED=$(git -C "$TELEMETRY_REPO" diff --name-only -- vignettes/data/ inst/extdata/telemetry/v1/ 2>/dev/null | wc -l | tr -d ' ')
UNTRACKED=$(git -C "$TELEMETRY_REPO" ls-files --others --exclude-standard -- vignettes/data/ inst/extdata/telemetry/v1/ 2>/dev/null | wc -l | tr -d ' ')
STAGED=$(git -C "$TELEMETRY_REPO" diff --cached --name-only -- inst/extdata/telemetry/v1/ 2>/dev/null | wc -l | tr -d ' ')

if [ "$CHANGED" -eq 0 ] && [ "$UNTRACKED" -eq 0 ] && [ "$STAGED" -eq 0 ]; then
  echo "TELEMETRY: no data changes"
  exit 0
fi

echo "TELEMETRY: $CHANGED changed, $UNTRACKED new data files, $STAGED staged parquets"

# ── Pull-rebase before push (JohnGavin/llmtelemetry#262) ──
echo "TELEMETRY: rebasing onto origin/main before push..."
if ! git -C "$TELEMETRY_REPO" fetch origin main 2>&1 | tail -3; then
  echo "TELEMETRY: fetch failed — skipping push (data committed locally)"
  exit 0
fi
if ! git -C "$TELEMETRY_REPO" pull --rebase --autostash origin main 2>&1 | tail -3; then
  echo "TELEMETRY: rebase conflict — aborting; bailing out without pushing"
  git -C "$TELEMETRY_REPO" rebase --abort 2>/dev/null || true
  exit 0
fi

# Commit data-only changes
git -C "$TELEMETRY_REPO" add vignettes/data/*.json
git -C "$TELEMETRY_REPO" commit -m "data: update telemetry data $(date +%Y-%m-%d)

Auto-exported from local sources (predictions, unified.duckdb, cmonitor-rs).
v1 parquets regenerated by run_rollup.R (#210).
Triggered by session-end hook." --no-verify 2>/dev/null

if [ $? -eq 0 ]; then
  # Push (triggers CI deploy)
  git -C "$TELEMETRY_REPO" push 2>/dev/null
  if [ $? -eq 0 ]; then
    echo "TELEMETRY: data pushed, CI will deploy"
  else
    echo "TELEMETRY: push failed (network?), data committed locally"
  fi
else
  echo "TELEMETRY: nothing to commit"
fi
